"""added project table

Revision ID: 8087f58bbdd6
Revises: b618d1018d1f
Create Date: 2019-12-05 13:04:52.891186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8087f58bbdd6'
down_revision = 'b618d1018d1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.String(length=60), nullable=True),
    sa.Column('project_address', sa.String(length=120), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_address')
    )
    op.create_index(op.f('ix_project_internal_id'), 'project', ['internal_id'], unique=True)
    op.create_index(op.f('ix_project_project_name'), 'project', ['project_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_project_name'), table_name='project')
    op.drop_index(op.f('ix_project_internal_id'), table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###
