"""adding current_project field to user

Revision ID: a4396d539821
Revises: 4261232aa91c
Create Date: 2019-12-10 10:46:57.625104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4396d539821'
down_revision = '4261232aa91c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_project', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'current_project')
    # ### end Alembic commands ###
